name: Check Incomplete Task List in PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_tasks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: thanh-doan-cirium/task-list-checker@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Get the pull request data using GitHub's API
      - name: Run task-list-checker
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Notify the user if the task check fails
    outputs:
      task_check_passed: ${{ steps.check-tasks.outcome }}
