name: Check Incomplete Task List in PR

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_tasks:
    runs-on: ubuntu-latest

    steps:
      # Run task list checker
      - name: Run task-list-checker
        id: check_tasks  # Give this step an ID
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Notify the user if the task check fails
    outputs:
      task_check_passed: ${{ steps.check_tasks.outcome }}  # Referencing the ID of the step that runs the check
